
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'MINUS NUMBER PLUSexpr : expr PLUS term\n            | expr MINUS termexpr : termterm : NUMBER'
    
_lr_action_items = {'NUMBER':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-3,-4,-1,-2,]),'PLUS':([1,2,3,6,7,],[4,-3,-4,-1,-2,]),'MINUS':([1,2,3,6,7,],[5,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),'term':([0,4,5,],[2,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr_plus_minus','Q8_parsing_algorithm_yacc.py',5),
  ('expr -> expr MINUS term','expr',3,'p_expr_plus_minus','Q8_parsing_algorithm_yacc.py',6),
  ('expr -> term','expr',1,'p_expr_term','Q8_parsing_algorithm_yacc.py',9),
  ('term -> NUMBER','term',1,'p_term_number','Q8_parsing_algorithm_yacc.py',12),
]
