
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'MINUS NUMBER PLUSE : E PLUS TE : E MINUS TE : TT : NUMBER'
    
_lr_action_items = {'NUMBER':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-3,-4,-1,-2,]),'PLUS':([1,2,3,6,7,],[4,-3,-4,-1,-2,]),'MINUS':([1,2,3,6,7,],[5,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,],[1,]),'T':([0,4,5,],[2,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E PLUS T','E',3,'p_r1','Q8_yacc.py',5),
  ('E -> E MINUS T','E',3,'p_r2','Q8_yacc.py',8),
  ('E -> T','E',1,'p_r3','Q8_yacc.py',11),
  ('T -> NUMBER','T',1,'p_r4','Q8_yacc.py',14),
]
